BASEDIR       = $(PTOOLS)
SRCDIR        = $(BASEDIR)/src
INCDIR        = $(BASEDIR)/inc
LIBDIR        = $(BASEDIR)/lib
BINDIR        = $(BASEDIR)/bin
EXESDIR       = $(BASEDIR)/exe
MACRODIR      = $(BASEDIR)/macros

# ROOT flags
include $(BASEDIR)/config/Makefile.arch

ROOTCFLAGS   := $(shell root-config --cflags)
ROOTLIBDIR   := $(shell root-config --libdir)
ROOTLIBS     := -L$(ROOTLIBDIR) -lCore -lRIO -lHist -lGpad -lTree -lPhysics -lMathCore 
